# Generated by Django 4.1.7 on 2024-01-11 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('photo', models.ImageField(upload_to='posts/')),
                ('caption', models.CharField(blank=True, max_length=1024, verbose_name='Caption')),
                ('likes', models.ManyToManyField(blank=True, null=True, to='core.users')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to='core.users')),
            ],
        ),
    ]
