# Generated by Django 4.1.7 on 2024-01-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Public'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(blank=True, to='core.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='followers',
            field=models.ManyToManyField(blank=True, to='core.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='following',
            field=models.ManyToManyField(blank=True, to='core.users'),
        ),
    ]
