# Generated by Django 4.1.7 on 2024-01-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='files',
        ),
        migrations.AddField(
            model_name='posts',
            name='files',
            field=models.FileField(default='', upload_to='posts/'),
            preserve_default=False,
        ),
    ]
