# Generated by Django 4.1.7 on 2024-01-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_posts_files_posts_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='files',
        ),
        migrations.AddField(
            model_name='posts',
            name='files',
            field=models.ManyToManyField(to='core.files'),
        ),
    ]
