# Generated by Django 4.1.7 on 2024-01-31 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=10, null=True, verbose_name='Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('incoming', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='core.users')),
                ('outgoing', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='core.users')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=25, verbose_name='Group name')),
                ('photo', models.ImageField(null=True, upload_to='pfps/')),
                ('admin', models.ManyToManyField(related_name='admin', to='core.users')),
                ('members', models.ManyToManyField(related_name='members', to='core.users')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=10, null=True, verbose_name='Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('incoming', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='gincoming', to='core.groups')),
                ('outgoing', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='goutgoing', to='core.users')),
            ],
        ),
    ]
