# Generated by Django 4.1.7 on 2024-02-10 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_messages_groups_groupmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageInstances',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=10, null=True, verbose_name='Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='messages',
            name='image',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='type',
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directmessages', to='core.messageinstances'),
        ),
    ]
