# Generated by Django 4.1.7 on 2024-02-10 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_messageinstances_remove_messages_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='type',
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupmessages', to='core.messageinstances'),
        ),
    ]
