# Generated by Django 4.1.7 on 2024-02-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_groupmessage_image_remove_groupmessage_type_and_more'),
    ]

    operations = [

    ]
