# Generated by Django 4.1.7 on 2024-02-10 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_groupmessage_image_groupmessage_type_and_more'),
    ]

    operations = [

    ]
