# Generated by Django 4.1.7 on 2024-02-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_groupmessage_image_remove_groupmessage_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupMessage',
        ),
    ]
