# Generated by Django 4.1.7 on 2024-02-10 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_groupmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('incoming', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='gincoming', to='core.groups')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupmessages', to='core.messageinstances')),
                ('outgoing', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='goutgoing', to='core.users')),
            ],
        ),
    ]
